version: '3'
name: laravel-project

services:

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx:latest
    ports:
      - 8070:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    container_name: nginx_container

  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - .:/var/www:cached
    container_name: php_container

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - .docker/phpmyadmin/sessions:/sessions

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refactorian
      MYSQL_USER: refactorian
      MYSQL_PASSWORD: refactorian

